args: !!python/object:argparse.Namespace
  accelerator: auto
  accumulate_grad_batches: null
  amp_backend: native
  amp_level: null
  arch: vit_base
  auto_lr_find: false
  auto_scale_batch_size: true
  auto_select_gpus: false
  batch_size: 32
  benchmark: null
  check_val_every_n_epoch: 1
  checkpoint_callback: null
  crop_min: 0.08
  data_dir: ../datasets/img
  default_root_dir: null
  detect_anomaly: false
  deterministic: true
  devices: auto
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  epochs: 100
  fast_dev_run: false
  flush_logs_every_n_steps: null
  gpus: null
  gradient_clip_algorithm: null
  gradient_clip_val: null
  ipus: null
  learning_rate: 0.6
  limit_predict_batches: null
  limit_test_batches: null
  limit_train_batches: null
  limit_val_batches: null
  log_every_n_steps: 50
  log_gpu_memory: null
  logger: true
  max_epochs: 1000
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  moco_dim: 256
  moco_mlp_dim: 4096
  moco_momentum: 0.99
  moco_momentum_cosine: true
  moco_temperature: 1.0
  momentum: 0.9
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 2
  optimizer_type: lars
  overfit_batches: 0.0
  persistent: true
  plugins: null
  precision: 32
  prepare_data_per_node: null
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  seed: 1234
  stochastic_weight_avg: false
  stop_grad_conv1: true
  strategy: ddp_spawn
  sync_batchnorm: true
  terminate_on_nan: null
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: null
  weight_decay: 1.0e-06
  weights_save_path: null
  weights_summary: top
  workers: 16
  worm_up_epochs: 10
